# Generated by Django 5.0.3 on 2024-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='data',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='data',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
