# Generated by Django 5.0.3 on 2024-03-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
